[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zhassyn Yegnay", email = "zhasynea@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "geopandas>=1.1.4",
    "networkx>=3.6.1",
    "osmnx>=2.1.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pyproj>=3.7.2",
    "pysolar>=0.13",
    "shapely>=2.1.2",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
